config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :books do
    resources :words do
      patch 'mastered', on: :member      
      patch 'unmastered', on: :member
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "books#index"
end

app/models/word.rb
# == Schema Information
# Schema version: 20231208053214
#
# Table name: words
#
#  id               :bigint           not null, primary key
#  definition       :text
#  example_sentence :text
#  name             :string
#  pronunciation    :string
#  slug             :string
#  status           :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  book_id          :bigint           not null
#
# Indexes
#
#  index_words_on_book_id  (book_id)
#
# Foreign Keys
#
#  fk_rails_...  (book_id => books.id)
#
class Word < ApplicationRecord
  extend FriendlyId
  belongs_to :book, touch: true, counter_cache: true
  has_one :user, through: :book
  has_rich_text :definition
  has_rich_text :example_sentence

  broadcasts_refreshes_to :user

  enum status: {  unmastered: 0, mastered: 1 }

  friendly_id :name, use: :slugged

  validates :name, presence: true
  normalizes :name, with: -> { _1.squish }

  after_initialize :set_default_status, if: :new_record?

  after_create do
    user = User.find(book.user_id)
    user.words_count = (user.words_count || 0) + 1
    user.save!
  end

  after_destroy do
    user = User.find(book.user_id)
    user.words_count = (user.words_count || 0) - 1
    user.save!
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name definition created_at status ] # replace with your actual Word attributes
  end


  private

  def set_default_status
    self.status ||= :unmastered
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_book
  before_action :set_word, only: %i[show edit update destroy unmastered mastered]


  def show
  end

  def new
    @word = @book.words.build
  end

  def edit
  end

  def create
    @word = @book.words.create! word_params
    if @word
      respond_to do |format|
        format.html { redirect_to book_path(@book), notice: "Word was successfully created."  }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update
    if @word.update! word_params
      respond_to do |format|
        format.html { redirect_to book_path(@book), notice: "Word was successfully updated."  }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @word
    @word.destroy!
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@word) }
        format.html { redirect_to book_path(@book), notice: 'word was delete..' }
    end
    else
      redirect_to book_path(@book), alert: '未找到该单词.'
    end
  end

  def mastered
    @word.update!(status: 1)
    redirect_to book_path(@book), notice: '单词标记已掌握'
  end

  def unmastered
    @word.update!(status: 0)
    redirect_to book_path(@book), notice: '单词标记未掌握.'
  end

  private
  def set_book
    @book = current_user.books.friendly.find(params[:book_id])
  end

  def set_word
    @word = @book.words.friendly.find_by(slug: params[:id])
  end

  def word_params
    params.require(:word).permit(:name, :definition, :example_sentence, :pronunciation, )
  end
end

app/helpers/words_helper.rb
module WordsHelper
  include Pagy::Frontend
end

app/views/words/_add_word_button.html.erb
<div class="flex justify-end m-5">
  <div class="inline-flex rounded-md shadow-sm" role="group" data-controller="checkbox-select">
    <button type="button" data-action="click->checkbox-select#deleteSelected" class="px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white">
      批量删除
    </button>
    <button  data-modal-target="new_modal" data-modal-toggle="new_modal" class="block text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
      创建单词
    </button>
  </div>
</div>
<%= render(NewModalComponent.new(title: "新建单词")) do %>
  <%= render 'words/word_form', book: @book, word: Word.new %>
<% end %>

app/views/words/_search_form.html.erb
<%= search_form_for search, url: book_path(book) do |f| %>
  <div class="grid gap-6 mb-6 md:grid-cols-2">
    <div>
      <%= f.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.search_field :name_cont, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-auto p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div>
      <%= f.label :definition, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.search_field :definition_cont, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-auto p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div>
      <%= f.label :status, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.select :status_eq, options_for_select(Word.statuses.keys), include_blank: 'All', class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-auto p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div class="block">
      <%= f.submit "search" %>
    </div>
  </div>
<% end %>

app/views/words/_update.turbo_stream.erb
<%= turbo_stream.replace nested_dom_id(book, word) do %>
  <%= render "words/word", book: book, word: word %>
<% end %>

app/views/words/_word.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600" id="<%= nested_dom_id(book, word)  %>">
  <td class="w-4 p-4">
    <div class="flex items-center">
      <input type="checkbox" data-checkbox-select-all-target="checkbox" value="<%= word.id %>" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
      <label class="sr-only">checkbox</label>
    </div>
  </td>
  <th scope="row" class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <%= word.name %>
  </th>
  <th scope="row" class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <% if word.mastered? %>
      <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-800"> 已</span>
    <% else %>
      <span class="bg-yellow-100 text-yellow-300 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300">否</span>
    <% end %>
  </th>
  <th scope="row" class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <time data-controller="timeago" data-timeago-datetime-value="<%= word.created_at %>" data-timeago-include-seconds-value="true" data-timeago-add-suffix-value="true"></time>
  </th>
  <td class="flex items-center px-4 py-2">
    <div class="items-center justify-center space-y-4 sm:flex sm:space-y-0 sm:space-x-4">
      <%= link_to "编辑", edit_book_word_path(book, word), data: { turbo_frame: 'modal' },  class:"px-3 py-2 mb-2 text-sm font-medium text-center text-blue-700 border border-blue-700 rounded-lg hover:text-white hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 me-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800" %>
      <button data-modal-target="popup-modal" data-modal-toggle="popup-modal" class="px-3 py-2 mb-2 text-sm font-medium text-center text-red-700 border border-red-700 rounded-lg hover:text-white hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 me-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900" type="button">
        删除
      </button>
      <div class="space-y-4 sm:flex sm:space-y-0 sm:space-x-4">
        <% if word.mastered? %>
          <%= button_to "未掌握", unmastered_book_word_path(book, word), method: :patch, class: "text-yellow-400 hover:text-white border border-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-3 py-2 text-center me-2 mb-2 dark:border-yellow-300 dark:text-yellow-300 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900" %>
        <% else %>
          <%= button_to "已掌握",  mastered_book_word_path(book, word), method: :patch,  class:"text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-3 py-2 text-center me-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800" %>
        <% end %>
      </div>
      <%= link_to '详情', book_word_path(book, word), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline hover:opacity-90 transition-opacity" %>
    </div>
  </td>
</tr>
<%= render DeletePopupComponent.new(objects: [book, word]) %>

app/views/words/_word_form.html.erb
<%= form_with(model: [book, word]) do |f| %>
  <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
    <div class="mt-2 mb-2 sm:col-span-2">
      <%= f.label :名称, for: "名称", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.text_field :name, type: "text", id: "name", placeholder: "单词名", required: true,
                  class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                  dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
    </div>
    <div class="mt-2 mb-2 sm:col-span-2">
      <%= f.label :发音, for: "发音", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.text_field :pronunciation, type: "text", id: "pronunciation", placeholder: "发音",
                  class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                  dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
    </div>
    <div class="mt-2 mb-2 sm:col-span-2">
      <%= f.label :例子, for: "例子", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.rich_text_area :example_sentence, id: "example_sentence",
                class:"block p-2.5 w-full text-sm
                      text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
                      dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
    </div>
    <div class="mt-2 mb-2 sm:col-span-2">
      <%= f.label :定义, for: "定义", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= f.rich_text_area :definition, id: "definition",
                class:"block p-2.5 w-full text-sm
                      text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
                      dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
    </div>
  </div>
  <div class="w-full mt-2 mb-2 border-t border-gray-200"></div>
  <div class="flex justify-center">
    <button type="button"
          class="inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white 
          bg-default-700  bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700
          rounded-lg hover:bg-gradient-to-br mr-2 mb-2" >
      <%= link_to "取消", book_path(book) %>
    </button>
    <button type="submit" 
              class="inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800 mr-2 mb-2"
          >
      <%= f.submit "确定" %>
    </button>
  </div>
<% end %>

app/views/words/_words.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg" data-controller="checkbox-select-all">
  <table class="w-full text-sm text-left text-gray-500 rtl:text-right dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="p-4">
          <div class="flex items-center">
            <input type="checkbox" data-checkbox-select-all-target="checkboxAll" data-action="input->checkbox-select-all#handleCheckboxAllChange" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
            <label  class="sr-only">checkbox</label>
          </div>
        </th>
        <th scope="col" class="px-6 py-3">
          <%= sort_link(@q, :name, "名称") %>
        </th>
        <th scope="col" class="px-6 py-3">
          是否掌握
        </th>
        <th scope="col" class="px-6 py-3">
          <%= sort_link(@q, :created_at, "添加时间") %>
        </th>
        <th scope="col" class="px-6 py-3">
          操作
        </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "words/word", locals: { book: book }, collection: words %>
    </tbody>
  </table>
</div>
<div class="flex justify-end mt-6 mr-4">
  <% if @pagy.count > @pagy.items %>
    <div class="">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/words/create.html.erb
<h1>Words#create</h1>
<p>Find me in app/views/words/create.html.erb</p>

app/views/words/create.turbo_stream.erb
<%= turbo_stream.update nested_dom_id(@book, Word.new), "" %>
<%= turbo_stream.append nested_dom_id(@book, "words") do %>
  <%= render "words/words", book: @book, words: @book.words %>
<% end %>

app/views/words/edit.html.erb
<%= render(TurboModalComponent.new(title: "编辑单词")) do %>
  <%= render 'words/word_form', book: @book, word: @word %>
<% end %>

app/views/words/index.html.erb
<h1>Words#index</h1>
<p>Find me in app/views/words/index.html.erb</p>

app/views/words/show.html.erb
<h1>Words#show</h1>
<p>Find me in app/views/words/show.html.erb</p>

app/views/words/update.html.erb
<h1>Words#update</h1>
<p>Find me in app/views/words/update.html.erb</p>

app/views/words/update.turbo_stream.erb
<%= render "words/update", book: @book, word: @word %>